language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - # default environment without variables
  - COMPOSER_DEPENDENCIES_OPTIONS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true

before_script:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source $COMPOSER_DEPENDENCIES_OPTIONS

script:
  - bin/parallel-lint -e php,phpt src tests
  - bin/phpcs -sp --standard=vendor/nella/coding-standard/Nella/ruleset.xml src tests
  - bin/phpunit --configuration tests/phpunit.xml tests
